[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#181b1e"     # tmux window-style bg
foreground = "#d3dbe3"     # tmux primary fg
dim_foreground = "#768390" # tmux inactive text

[colors.cursor]
text = "#181b1e"
cursor = "#d3dbe3"

[colors.selection]
text = "#d3dbe3"
background = "#2d333b"     # tmux copy/search bg

[colors.normal]
black   = "#181b1e"
red     = "#ff7a93"
green   = "#9cee82"
yellow  = "#ffc777"
blue    = "#7da6ff"
magenta = "#d7a1f9"
cyan    = "#5de4c7"
white   = "#d3dbe3"

[colors.bright]
black   = "#373e47"        # pane borders / separators
red     = "#ff7a93"
green   = "#9cee82"
yellow  = "#ffc777"
blue    = "#7da6ff"
magenta = "#d7a1f9"
cyan    = "#5de4c7"
white   = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#2d333b"

[[colors.indexed_colors]]
index = 17
color = "#768390"

# [cursor]
# blink_interval = 500
# blink_timeout = 5
# unfocused_hollow = false

# [cursor.style]
# blinking = "On"
# shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
# program = "/usr/bin/zsh"
program = "/usr/bin/env"
args = ["bash", "-i", "-c", "$HOME/.local/bin/ts-create $HOME"]

[window]
# dimensions = { columns = 2, lines = 0 }
padding = { x = 0, y = 0 }
decorations = "None"
dynamic_title = true
dynamic_padding = true
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
